development:
  secret_key_base: secret-key-base
  mailgun_api_key: mailgun-api-key
  mailgun_validation_key: mailgun-validation-key

test:
  secret_key_base: secret-key-base
  mailgun_api_key: mailgun-api-key
  mailgun_validation_key: mailgun-validation-key
